Array as json string
sbtqa/api-factory pull request #16
Opened 2017-09-12 05:45 UTC by 0I0u3uk

Api factory научился подставлять в шаблон прям куски json, но пришлось добавить api.dependent.array.separator в качестве разделителя элементов массива

2017-09-12 05:50 UTC, kosteman approved these changes

2017-09-15 02:19 UTC, clicman requested changes

2017-09-15 02:19 UTC, clicman commented on .travis.yml
>    - provider: script
Add TODO please. To not forget to revert it back later

2017-09-15 02:58 UTC, kosteman approved these changes

2017-09-15 03:05 UTC, merged